sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb

sonata_block:
    blocks:
        #...
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_admin:
    templates:
        layout:                AdminBundle::standard_layout.html.twig
        knp_menu_template:     AdminBundle:Menu:sonata_menu.html.twig
        list:                  AdminBundle:CRUD:list.html.twig

    dashboard:
        groups:
            sonata_user:
                roles: [ROLE_SUPER_ADMIN]
                label: 'Seguridad y acceso'
                icon:   '<i class="fa fa-lock"></i>'
        
