<?php

namespace LogicBundle\Repository;

/**
 * AtributoDisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoDisciplinaRepository extends \Doctrine\ORM\EntityRepository {
    
}
