<?php

namespace LogicBundle\Repository;

/**
 * BonificacionJuzgamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonificacionJuzgamientoRepository extends \Doctrine\ORM\EntityRepository {
    
}
