<?php

namespace LogicBundle\Repository;

/**
 * CaracterizacionUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracterizacionUsuarioRepository extends \Doctrine\ORM\EntityRepository {
    
}
