<?php

namespace LogicBundle\Repository;

/**
 * CategoriaRamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRamaRepository extends \Doctrine\ORM\EntityRepository {
    
}
