<?php

namespace LogicBundle\Repository;

/**
 * EstadoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoContratoRepository extends \Doctrine\ORM\EntityRepository {
    
}
