<?php

namespace LogicBundle\Repository;

/**
 * ItemDesempateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemDesempateRepository extends \Doctrine\ORM\EntityRepository {
    
}
