<?php

namespace LogicBundle\Repository;

/**
 * JustificacionWRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificacionWRepository extends \Doctrine\ORM\EntityRepository {
    
}
