<?php

namespace LogicBundle\Repository;

/**
 * JustificacionPartidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificacionPartidoRepository extends \Doctrine\ORM\EntityRepository {
    
}
