<?php

namespace LogicBundle\Repository;

/**
 * MatrizProgramacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrizProgramacionRepository extends \Doctrine\ORM\EntityRepository {
    
}
