<?php

namespace LogicBundle\Repository;

/**
 * ModalidadEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalidadEventoRepository extends \Doctrine\ORM\EntityRepository {
    
}
