<?php

namespace LogicBundle\Repository;

/**
 * MotivoResevaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoResevaRepository extends \Doctrine\ORM\EntityRepository {
    
}
