<?php

namespace LogicBundle\Repository;

/**
 * ObservacionEscenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionEscenarioRepository extends \Doctrine\ORM\EntityRepository {
    
}
