<?php

namespace LogicBundle\Repository;

/**
 * SistemaPuntajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaPuntajeRepository extends \Doctrine\ORM\EntityRepository {
    
}
