<?php

namespace LogicBundle\Repository;

/**
 * SubcategoriaDisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaDisciplinaRepository extends \Doctrine\ORM\EntityRepository {
    
}
