<?php

namespace LogicBundle\Repository;

/**
 * TerminosYCondicionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminosYCondicionesRepository extends \Doctrine\ORM\EntityRepository {
    
}
