<?php

namespace LogicBundle\Repository;

/**
 * TerminosYCondicionesEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminosYCondicionesEventoRepository extends \Doctrine\ORM\EntityRepository {
    
}
