<?php

namespace LogicBundle\Repository;

/**
 * TipoRecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRecursoRepository extends \Doctrine\ORM\EntityRepository {
    
}
