<?php

namespace LogicBundle\Repository;

/**
 * TipoJustificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoJustificacionRepository extends \Doctrine\ORM\EntityRepository {
    
}
