<?php

namespace LogicBundle\Repository;

/**
 * TipoPuntajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPuntajeRepository extends \Doctrine\ORM\EntityRepository {
    
}
