<?php

namespace LogicBundle\Repository;

/**
 * TorneoBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorneoBaseRepository extends \Doctrine\ORM\EntityRepository {
    
}
